"""empty message

Revision ID: 86ba0be2ea62
Revises: 649e7394acb5
Create Date: 2024-01-21 22:51:59.929741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ba0be2ea62'
down_revision = '649e7394acb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('quote',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('client',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis', schema=None) as batch_op:
        batch_op.alter_column('client',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('quote',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
