"""empty message

Revision ID: c73e6a24f1db
Revises: 
Create Date: 2024-02-16 21:01:44.320633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c73e6a24f1db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('quote', sa.Integer(), nullable=False),
    sa.Column('client', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('histolossfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('vintage', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('premium', sa.Integer(), nullable=False),
    sa.Column('agg_limit', sa.Integer(), nullable=False),
    sa.Column('agg_deduct', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modelfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('premiumfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('riskprofilefile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('analysis_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['analysis.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('histoloss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('premium', sa.Integer(), nullable=True),
    sa.Column('loss', sa.Integer(), nullable=True),
    sa.Column('loss_ratio', sa.Float(), nullable=True),
    sa.Column('lossfile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lossfile_id'], ['histolossfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layermodelfile',
    sa.Column('layer_id', sa.Integer(), nullable=False),
    sa.Column('modelfile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['layer_id'], ['layer.id'], ),
    sa.ForeignKeyConstraint(['modelfile_id'], ['modelfile.id'], ),
    sa.PrimaryKeyConstraint('layer_id', 'modelfile_id')
    )
    op.create_table('modelyearloss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('loss_ratio', sa.Float(), nullable=True),
    sa.Column('modelfile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['modelfile_id'], ['modelfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('premium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('premiumfile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['premiumfile_id'], ['premiumfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultlayer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('premium', sa.Integer(), nullable=False),
    sa.Column('agg_limit', sa.Integer(), nullable=False),
    sa.Column('agg_deduct', sa.Integer(), nullable=False),
    sa.Column('resultfile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resultfile_id'], ['resultfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultmodelfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_src', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('resultfile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resultfile_id'], ['resultfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('riskprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('riskprofilefile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['riskprofilefile_id'], ['riskprofilefile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultlayermodelfile',
    sa.Column('resultlayer_id', sa.Integer(), nullable=False),
    sa.Column('resultmodelfile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resultlayer_id'], ['resultlayer.id'], ),
    sa.ForeignKeyConstraint(['resultmodelfile_id'], ['resultmodelfile.id'], ),
    sa.PrimaryKeyConstraint('resultlayer_id', 'resultmodelfile_id')
    )
    op.create_table('resultlayeryearloss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('loss_ratio', sa.Float(), nullable=True),
    sa.Column('gross', sa.Integer(), nullable=True),
    sa.Column('ceded', sa.Integer(), nullable=True),
    sa.Column('net', sa.Integer(), nullable=True),
    sa.Column('resultlayer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resultlayer_id'], ['resultlayer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultmodelyearloss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('loss_ratio', sa.Float(), nullable=True),
    sa.Column('resultmodelfile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resultmodelfile_id'], ['resultmodelfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultmodelyearloss')
    op.drop_table('resultlayeryearloss')
    op.drop_table('resultlayermodelfile')
    op.drop_table('riskprofile')
    op.drop_table('resultmodelfile')
    op.drop_table('resultlayer')
    op.drop_table('premium')
    op.drop_table('modelyearloss')
    op.drop_table('layermodelfile')
    op.drop_table('histoloss')
    op.drop_table('riskprofilefile')
    op.drop_table('resultfile')
    op.drop_table('premiumfile')
    op.drop_table('modelfile')
    op.drop_table('layer')
    op.drop_table('histolossfile')
    op.drop_table('analysis')
    # ### end Alembic commands ###
